org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
org.gradle.configuration-cache=false
fabric.loom.dropNonIntermediateRootMethods=true

mod.id=eg_fix_horizontal_camera_lag
mod.name=Fix Horizontal Camera Lag
mod.description=Disconnects the horizontal camera movement from the entity you are riding, eliminating the lag when looking around and riding something.\nThis mod fixes both MC-259512 and MC-122731\n\nWarning: use this at your own risk on multiplayer servers. In most cases you should be fine but this mod may give you a slight advantage because of the nature of what it does. Check with the server owner before using. I am not responsible for any bans given by using this mod.
mod.group=games.enchanted
mod.version=1.2.1
mod.license=CC BY-NC 4.0
mod.source_url=https://github.com/Enchanted-Games/fix-horizontal-camera-lag
mod.issue_tracker=https://github.com/Enchanted-Games/fix-horizontal-camera-lag/issues
mod.icon=assets/eg_fix_horizontal_camera_lag/icon.png

deps.minecraft=[VERSIONED]
dep_str.minecraft=[VERSIONED]

deps.fabric-loader=0.18.4
dep_str.fabric-loader=>=0.18

deps.fabric-api=[VERSIONED]
dep_str.fabric-api=[VERSIONED]

deps.neoforge=[VERSIONED]

publish.dry_run=true
# Uncomment and enter modrinth or curseforge project ids to enable publishing
publish.modrinth=TuB934hI
#publish.curseforge=
#publish.additionalVersions=[VERSIONED]